name: mobile
description: "Online XOX Game Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # WebSocket
  socket_io_client: ^2.0.3+1

  # Code Generation
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Localization
  easy_localization: ^3.0.3

  # Utils
  equatable: ^2.0.5
  uuid: ^4.2.2

  # Dependency Injection
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
